# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT NaturalMexico.wsgi

beta_settings:
    cloud_sql_instances: pruebadjango-178220:us-central1:pruebadjango-060697

runtime_config:
  python_version: 3
# [END runtime]
