# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import inicio.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_admin', models.BooleanField(default=False, verbose_name='administrador')),
                ('is_personal', models.BooleanField(default=False, verbose_name='Personal')),
                ('avatar', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
            managers=[
                ('objects', inicio.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('peso_neto', django_mysql.models.EnumField(choices=[('t', 'Si'), ('f', 'No')])),
                ('color', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('tamanio', django_mysql.models.EnumField(choices=[('c', 'Chico'), ('m', 'Mediano'), ('g', 'Grande')])),
                ('alto', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('ancho', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('largo', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('IDCliente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('rfc', models.CharField(max_length=13)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('fecha_inclusion', models.DateTimeField(auto_now_add=True, verbose_name='dia_creado')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_cajas', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('IDEmpleado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('rfc', models.CharField(max_length=13)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('fecha_indusion', models.DateTimeField(auto_now_add=True, verbose_name='dia_creado')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Huerto',
            fields=[
                ('IDHuerto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('numero_hectareas', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('numero_tablas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='dia_creado')),
                ('monto', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('tipo_cambio', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='dia_creado')),
                ('preciokg', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('tipo', django_mysql.models.EnumField(choices=[('c', 'Compra'), ('v', 'Venta')])),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('IDProducto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCampo',
            fields=[
                ('IDProductoCampo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('calidad_aprox', django_mysql.models.EnumField(choices=[('e', 'Excelente'), ('b', 'Buena'), ('r', 'Regular'), ('m', 'Mala')])),
                ('fecha_recepcion', models.DateTimeField(null=True, verbose_name='dia_creado')),
                ('firma', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('representante', models.CharField(max_length=100)),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCorrida',
            fields=[
                ('IDProductoCorrida', models.AutoField(primary_key=True, serialize=False)),
                ('calibre', models.CharField(choices=[('pruebs', 'prueba'), ('prueba1', 'prueba')], max_length=100)),
                ('kilogramos', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('fecha_inclusion', models.DateTimeField(auto_now_add=True, verbose_name='dia_creado')),
                ('fecha_compra', models.DateField(verbose_name='dia_creado')),
                ('folio', models.CharField(max_length=100)),
                ('Detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.Detalle')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Producto')),
                ('ProductoCampo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.ProductoCampo')),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('IDProductor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('rfc', models.CharField(max_length=13)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('fecha_inclusion', models.DateTimeField(verbose_name='dia_creado')),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('IDPrueba', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('kilogramos', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('Caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Caja')),
            ],
        ),
        migrations.CreateModel(
            name='Status_pc',
            fields=[
                ('IDStatus_pc', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='dia_creado')),
                ('estado', django_mysql.models.EnumField(choices=[('p', 'Pendiente'), ('r', 'Reposo'), ('c', 'Completada'), ('a', 'Pagada')])),
                ('IDProductoCampo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.ProductoCampo')),
            ],
        ),
        migrations.CreateModel(
            name='Status_pco',
            fields=[
                ('IDStatus_pc', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='dia_creado')),
                ('estado', django_mysql.models.EnumField(choices=[('f', 'Camara Fria'), ('a', 'Almacen'), ('c', 'Camino'), ('e', 'Entregada')])),
                ('IDProductoCampo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.ProductoCorrida')),
            ],
        ),
        migrations.AddField(
            model_name='productocampo',
            name='Productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Productor'),
        ),
        migrations.AddField(
            model_name='precio',
            name='ProductoCorrida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.ProductoCorrida'),
        ),
        migrations.AddField(
            model_name='huerto',
            name='Productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Productor'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='OrdenCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.OrdenCompra'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Producto'),
        ),
        migrations.AddField(
            model_name='caja',
            name='ProductoCampo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.ProductoCampo'),
        ),
    ]
