# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huerto',
            name='numero_hectareas',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='productor',
            name='fecha_inclusion',
            field=models.DateTimeField(verbose_name='dia_creado'),
        ),
    ]
