# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 23:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocampo',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='dia_creado'),
        ),
    ]
