# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20170824_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huerto',
            name='numero_hectareas',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
