# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20170824_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocampo',
            name='calidad_aprox',
            field=django_mysql.models.EnumField(choices=[('1', 'Excelente'), ('2', 'Buena'), ('3', 'Regular'), ('4', 'Mala')]),
        ),
        migrations.AlterField(
            model_name='productocampo',
            name='firma',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
