# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20171022_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibre',
            fields=[
                ('IDCalibre', models.AutoField(primary_key=True, serialize=False)),
                ('Valor', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='productocorrida',
            name='calibre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Calibre'),
        ),
    ]
