# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20171022_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocorrida',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True, verbose_name='dia_creado'),
        ),
    ]
