# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20170826_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='alto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caja',
            name='ancho',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caja',
            name='largo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caja',
            name='tamanio',
            field=django_mysql.models.EnumField(choices=[('c', 'Chico'), ('m', 'Mediano'), ('g', 'Grande')]),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='monto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='precio',
            name='preciokg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='precio',
            name='tipo',
            field=django_mysql.models.EnumField(choices=[('c', 'Compra'), ('v', 'Venta')]),
        ),
        migrations.AlterField(
            model_name='productocampo',
            name='calidad_aprox',
            field=django_mysql.models.EnumField(choices=[('e', 'Excelente'), ('b', 'Buena'), ('r', 'Regular'), ('m', 'Mala')]),
        ),
        migrations.AlterField(
            model_name='productocampo',
            name='status',
            field=django_mysql.models.EnumField(choices=[('t', 'Terminada'), ('p', 'En proceso'), ('e', 'Entregada')]),
        ),
        migrations.AlterField(
            model_name='productocorrida',
            name='IDProductoCorrida',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productocorrida',
            name='kilogramos',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productocorrida',
            name='status',
            field=django_mysql.models.EnumField(choices=[('t', 'Terminada'), ('p', 'En proceso'), ('e', 'Entregada')]),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='kilogramos',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
