# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_auto_20170827_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
