# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_auto_20170902_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocorrida',
            name='fecha_compra',
            field=models.DateTimeField(verbose_name='dia_creado'),
        ),
    ]
