# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_auto_20170907_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocorrida',
            name='Detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.Detalle'),
        ),
        migrations.AlterField(
            model_name='productocorrida',
            name='fecha_compra',
            field=models.DateField(verbose_name='dia_creado'),
        ),
    ]
